inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 4.0
  NewCops: disable
  SuggestExtensions: false
  Include:
    - "Gemfile"
    - "Rakefile"
    - "backup.gemspec"
  Exclude:
    - "tmp/**/*"
    - "vagrant/**/*"
    # Necessary on travis CI
    - "vendor/**/*"
  DisplayCopNames: true
  UseCache: true
  CacheRootDirectory: ./tmp

# Metrics/LineLength:
#   Max: 80

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/HashSyntax:
  EnforcedStyle: ruby19

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/FormatString:
  EnforcedStyle: sprintf

Style/SymbolArray:
  Enabled: false
