source "https://rubygems.org"

gem 'rake'

# MySQL, PostgreSQL
gem 'activerecord'
gem 'activerecord-mysql2-adapter'
gem 'iconv'
gem 'pg'

# MongoDB
gem 'mongo'
gem 'bson_ext'

# Redis
gem 'redis'

# Riak
# Keep the utility bundle compatible with its Ruby 1.9.3 test environment.
gem 'i18n', '~> 0.8.0'
gem 'riak-client'
