source "https://rubygems.org"

ruby '>= 3.2.0'

gem 'rake', '~> 13.2'

# MySQL, PostgreSQL
gem 'activerecord', '~> 7.2.3', '>= 7.2.3.1'
gem 'mysql2', '~> 0.5'
gem 'pg', '~> 1.6'

# MongoDB
gem 'mongo', '~> 2.25'

# Redis
gem 'redis'

# Riak
gem 'riak-client'

group :test do
  gem 'rspec', '~> 3.13'
end
