source "https://rubygems.org"

ruby '>= 3.1.0'

gem 'rake', '~> 13.0'

# MySQL, PostgreSQL
gem 'activerecord', '~> 7.2.3', '>= 7.2.3.1'
gem 'mysql2', '~> 0.5'
gem 'pg', '~> 1.6'

# MongoDB
gem 'mongo'
gem 'bson_ext'

# Redis
gem 'redis'

# Riak
gem 'riak-client'
