name: lint
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'bin/*'
      - '**.rb'
      - '**.rake'
      - '**/Rakefile'
      - '.github/workflows/rubocop.yml'
jobs:
  rubocop:
    runs-on: ubuntu-22.04
    env:
      BUNDLE_WITHOUT: no_ci
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get install -qf libcurl4-openssl-dev
      - name: Install ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '4.0.6'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rubocop
